### PR TITLE
Pull Beta to Master

### PR DESCRIPTION
**Pull request by asolsonaberga**
Hi @kfrasier and @jahildebrand 

I was thinking to pull the Beta brunch to the master branch.
Finally, all the changes are done. Now, `detEdit` can be safely used all the way to `modDet`. From `modDet` you can call different options to show plots or not of peak-to-peak and ICI. I will add to the manual the new options that detEdit has. 
These following weeks I will focus on the next steps. I already create a brunch called modify-code-to-create-log-files. Once I am done, I will request another pull to the master branch, which then, you can review and accept if you think is good.  

The best will be if we learn how to make this branches to be able to change the code. I can help you on how to do that now that I understand better how GitHub works. It will make the code accessible to use while we are still working on it.

### CODE REVIEW

**Comment by kfrasier** [comment]
Yeah, I agree. Branching will help us work on improvements without breaking things for everyone. 

I'm not sure how this pull request will go through though, with the conflicts? 
Might have to do a hard reset or something, to override them. I think that can only be done in the command line. Happy to help if needed.

**Comment by asolsonaberga** [comment]
Hi Kait!

If you around today, maybe we could look at this together. I was looking at the conflicts but they are hard to track from here.

**Comment by kfrasier** [comment]
Hi Alba,

I am around and I’ll try to stop by this afternoon. I think we need to do
something like this:

http://git.tutorialhorizon.com/2014/10/05/replace-the-master-branch-with-another-branch-in-git/

Where their feature_branch is our Beta branch.

I’m not sure if the command line tools got installed for you with the
desktop app or not. I think so?

Anyway, I’ll check in this afternoon and see where you’re at :)

-Kait

**Comment by asolsonaberga** [comment]
I do not have the command line tools. Which one are you using?

**Comment by kfrasier** [comment]
It should have installed something called Git Shell, if you search your
applications.

But I've also got this one: https://git-scm.com

**Comment by asolsonaberga** [comment]
I found this easy way to do it from the website

https://www.youtube.com/watch?v=cIw0aOyXUcg

But I will install the git

**Comment by asolsonaberga** [comment]
I solved all the conflicts!! And will proceed on merging the pull request.

**Comment by asolsonaberga** [comment]
I will proceed on deleting the Beta branch!!!! We should be able to use the new detEdit from the master branch

**Pull request merged**
